project:
  type: book
  output-dir: ../docs

book:
  title: "CMPT 419"
  author: "Nicholas Vincent"
  date: "9/3/2025"
  chapters:
    - index.qmd
    - 01_syllabus.qmd
    - 02_readings.qmd
    - 03_assignments.qmd
    - 04_slides.qmd
    - project_proposal.qmd
    - project.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



