# Preface {.unnumbered}

This website contains the CMPT 419 / 980 Fall 2025 Course Materials. It was produced using "Quarto".

To learn more about Quarto books visit <https://quarto.org/docs/books>.

## Outline

You can find the course outline [here](https://www.sfu.ca/outlines.html?2025/fall/cmpt/419/d200). The content will also be pasted at the end of this Introduction Chapter for your convenience.

## Syllabus and Course Content

If there's anything you're looking for you can't find in this site, check the Canvas homepage -- all internal-facing content is there (lecture recordings, notes, etc.).

The syllabus file describe the overall structure of the course and course policies.

The readings page will be updated weekly.

I will post coding assignments here as the semester goes in (note that assignments from previous offerings are online, as I make these GitHub pages public. Some changes will be made to the assignments). The GitHub will list the requirements and grading scheme. Submission will be via Canvas.


## Outline Text

Artificial intelligence (AI) technologies have seen a large surge in interest from researchers, investors, businesses, and everyday end-users. These technologies stand on the shoulders of giants -- they rely on a large body of research in computing and other fields, as well as modern feats of engineering from organizations that operate them. However, they also rely heavily on data, and thus, people.

Search engines rely on click data from users and content written by volunteers such as blogs and Wikipedia articles. Recommender systems rely on explicit user feedback (e.g., “star ratings”) and behavioral data (e.g., browsing history) that reveal user preferences. Supervised learning relies on crowd workers, volunteers, and sometimes unwitting users (e.g., reCAPTCHA participants) to label images and text. And new generative AI systems rely on the wide swathe of content shared on the web. Without this data generated by the public, technologies that use machine learning and statistical models could not exist. The critical role of data suggests an untapped source of power for data creators, i.e., the broad public. Furthermore, it suggests a number of exciting questions about how a data-centric view can advance both AI research and the development of AI products and other systems.

In this course, we will explore AI technologies with a data-centric, and thus human-centric lens. We will discuss topics such as:
- Exposure to foundational reading in interdisciplinary AI
- The intersection of humanities scholarship and technical computing aspects of AI
- Modern research in data valuation
- Relevant work in social computing, including the impact of online platform design choices.
- The potential for collective action involving data. How might social movements -- ranging from protests that withhold data to movements to collect and share data in the public interest -- impact the future of AI?
- The economics of data. Students will be introduced to recent work on data markets and unique properties of buying/selling data for AI.

We will read papers on these topics together. Students will work together to synthesize and present knowledge from research papers, and present their own opinions on these topics. The course will centre a structured final project that will enable students to conduct interdisciplinary responsible AI research or bring responsible AI concepts to bear in industry contexts.

Students may benefit from having taken a course in AI, ML, or data science (or have equivalent experience from e.g. an internship, a research project, a personal project).

Example SFU courses:
CMPT 310 - Intro Artificial Intelligence
CMPT 353 - Computational Data Science
CMPT 414 - Computer Vision

Having taken an HCI course or relevant social science course (e.g., sociology, economics) is a plus, but CS students without this experience who want to explore interdisciplinary CS work that is “human-centered” are welcome. Similarly, students in the humanities who have some exposure to data science are also welcome.

We will work through a low-stakes "example assignment" in week 1 so that students can assess their comfort level.

In short, students should ideally be decently comfortable with both (1) working with computational notebooks (Python, R, Julia, etc.), quickly loading and working with quantitative data, training and evaluating machine learning models and (2) reading and critically thinking about new scholarly perspectives and ethical considerations.

This course will include a heavy reading component.

The course will aim to develop the following skills:
- students will become more comfortable reading research papers that take an interdisciplinary approach to study AI
- students will gain experience presenting information from papers
- there will be a project component that incorporates coding
- students will be able to articulate some of the ongoing challenges in “human-centric” AI.

Students will gain exposure to the following concepts:
- interdisciplinary research in AI
- data valuation techniques, and their applications for AI research/practice
- social computing


